<a href="https://colab.research.google.com/github/yogeshns1924/python-practices-/blob/main/Pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv("Titanic.csv")
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  37.0      0
887                       Graham, Miss. Margaret Edith  female  34.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female  28.0      1
889                              Behr, Mr. Karl Howell    male  19.0      0
890                                Dooley, Mr. Patrick    male  48.0      0

     Parch            Ticket     Fare    Cabin Embarked
0        0         A/5 21171   7.2500      C85        S
1        0          PC 17599  71.2833     C123        C
2        0  STON/O2. 3101282   7.9250      E46        S
3        0            113803  53.1000       G6        S
4        0            373450   8.0500     C103        S
..     ...               ...      ...      ...      ...
886      0            211536  13.0000     E121        S
887      0            112053  30.0000      B77        C
888      2        W./C. 6607  23.4500  B96 B98        Q
889      0            111369  30.0000      D11        C
890      0            370376   7.7500      E77        S

[891 rows x 12 columns]

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,C85,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C123,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,E46,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,G6,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,C103,S

In [ ]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,37.0,0,0,211536,13.00,E121,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,34.0,0,0,112053,30.00,B77,C
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.45,B96 B98,Q
889,890,1,1,"Behr, Mr. Karl Howell",male,19.0,0,0,111369,30.00,D11,C
890,891,0,3,"Dooley, Mr. Patrick",male,48.0,0,0,370376,7.75,E77,S

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df.shape

(891, 12)

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,30.560606,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,16.697818,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.000000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,40.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,221.000000,8.000000,6.000000,512.329200

In [ ]:
df["Age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    37.0
887    34.0
888    28.0
889    19.0
890    48.0
Name: Age, Length: 891, dtype: float64

In [ ]:
df[["Age","Survived"]]

      Age  Survived
0    22.0         0
1    38.0         1
2    26.0         1
3    35.0         1
4    35.0         0
..    ...       ...
886  37.0         0
887  34.0         1
888  28.0         0
889  19.0         1
890  48.0         0

[891 rows x 2 columns]

In [ ]:
df[df["Age"]>35]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C123,C
5,6,0,3,"Moran, Mr. James",male,54.0,0,0,330877,8.4583,D56,Q
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,58.0,1,1,PP 9549,16.7000,B30,S
12,13,0,3,"Saundercock, Mr. William Henry",male,39.0,0,0,A/5. 2151,8.0500,B28,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,55.0,0,0,350406,7.8542,F33,S
...,...,...,...,...,...,...,...,...,...,...,...,...
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,54.0,0,1,11767,83.1583,B5,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,45.0,0,0,7552,10.5167,C46,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,45.0,0,0,SOTON/OQ 392076,7.0500,B22,S
886,887,0,2,"Montvila, Rev. Juozas",male,37.0,0,0,211536,13.0000,E121,S
890,891,0,3,"Dooley, Mr. Patrick",male,48.0,0,0,370376,7.7500,E77,S

In [ ]:
df[(df["Age"] > 35)& (df["Sex"] =='male')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,54.0,0,0,330877,8.4583,D56,Q
12,13,0,3,"Saundercock, Mr. William Henry",male,39.0,0,0,A/5. 2151,8.0500,B28,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,42.0,3,2,19950,263.0000,C123,S
46,47,0,3,"Lennon, Mr. Denis",male,38.0,1,0,370371,15.5000,C78,Q
73,74,0,3,"Chronopoulos, Mr. Apostolos",male,59.0,1,0,2680,14.4542,B18,S
...,...,...,...,...,...,...,...,...,...,...,...,...
872,873,0,1,"Carlsson, Mr. Frans Olof",male,75.0,0,0,695,5.0000,C90,C
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,45.0,0,0,345765,9.0000,C124,C
884,885,0,3,"Sutehall, Mr. Henry Jr",male,45.0,0,0,SOTON/OQ 392076,7.0500,B22,S
886,887,0,2,"Montvila, Rev. Juozas",male,37.0,0,0,211536,13.0000,E121,S
890,891,0,3,"Dooley, Mr. Patrick",male,48.0,0,0,370376,7.7500,E77,S

In [ ]:
df[df["Survived"]==1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C123,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,E46,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,G6,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,14.0,0,2,347742,11.1333,B78,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,21.0,1,0,237736,30.0708,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,38.0,0,0,2667,7.2250,F G73,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,54.0,0,1,11767,83.1583,B5,S
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,12.0,0,1,230433,26.0000,B101,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,34.0,0,0,112053,30.0000,B77,C
889,890,1,1,"Behr, Mr. Karl Howell",male,19.0,0,0,111369,30.0000,D11,C

In [ ]:
df[(df["Survived"]==1) & (df["Age"] > 30)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C123,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,G6,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,58.0,1,1,PP 9549,16.7000,B30,S
17,18,1,2,"Williams, Mr. Charles Eugene",male,35.0,0,0,244373,13.0000,E31,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,38.0,0,0,330923,8.0292,B58 B60,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
858,859,1,3,"Baclini, Mrs. Solomon (Latifa Qurban)",female,48.0,0,3,2666,19.2583,C47,S
866,867,1,2,"Duran y More, Miss. Asuncion",female,45.0,1,0,SC/PARIS 2149,13.8583,C50,S
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,38.0,0,0,2667,7.2250,F G73,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,54.0,0,1,11767,83.1583,B5,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,34.0,0,0,112053,30.0000,B77,C

In [ ]:
df.loc[2,"Name"]

'Heikkinen, Miss. Laina'

In [ ]:
df.loc[0:1,["Name","Age"]]

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0

In [ ]:
df.iloc[0,1]

np.int64(0)

In [ ]:
df[["Name","Age"]]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  37.0
887                       Graham, Miss. Margaret Edith  34.0
888           Johnston, Miss. Catherine Helen "Carrie"  28.0
889                              Behr, Mr. Karl Howell  19.0
890                                Dooley, Mr. Patrick  48.0

[891 rows x 2 columns]

In [ ]:
df[df["Age"]>40]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,54.0,0,0,330877,8.4583,D56,Q
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,58.0,1,1,PP 9549,16.7000,B30,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,55.0,0,0,350406,7.8542,F33,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,66.0,1,5,347077,31.3875,F E69,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,42.0,3,2,19950,263.0000,C123,S
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,45.0,0,0,345765,9.0000,C124,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,54.0,0,1,11767,83.1583,B5,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,45.0,0,0,7552,10.5167,C46,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,45.0,0,0,SOTON/OQ 392076,7.0500,B22,S
890,891,0,3,"Dooley, Mr. Patrick",male,48.0,0,0,370376,7.7500,E77,S

In [ ]:
df[df["PassengerId"]==5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.05,C103,S

In [ ]:
df[(df["Age"]>40) |(df["Survived"]==2)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,54.0,0,0,330877,8.4583,D56,Q
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,58.0,1,1,PP 9549,16.7000,B30,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,55.0,0,0,350406,7.8542,F33,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,66.0,1,5,347077,31.3875,F E69,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,42.0,3,2,19950,263.0000,C123,S
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,45.0,0,0,345765,9.0000,C124,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,54.0,0,1,11767,83.1583,B5,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,45.0,0,0,7552,10.5167,C46,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,45.0,0,0,SOTON/OQ 392076,7.0500,B22,S
890,891,0,3,"Dooley, Mr. Patrick",male,48.0,0,0,370376,7.7500,E77,S

In [ ]:
df.loc[0:0,["Name","Age"]]

                      Name   Age
0  Braund, Mr. Owen Harris  22.0

In [ ]:
df.iloc[0,0]

np.int64(1)

In [ ]:
df.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,False,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,False,False,False,False,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64