<a href="https://colab.research.google.com/github/yogeshns1924/python-practices-/blob/main/Pandas_Task_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
s=pd.Series(["arun","yoga","kumar","shree","lokesh"])
print(s)

0      arun
1      yoga
2     kumar
3     shree
4    lokesh
dtype: object

In [ ]:
data = {
    "Name": ["Arun", "Yoga", "Kumar", "Shree", "Lokesh","Nsy"],
    "Age": [21, 22, 20, 23, None,23],
    "Gender": ["Male", "Male", "Male", "Female", "Male","Male"],
    "Department": ["CSE", "ECE", "CSE", "CSE", "IT","CSE"],
    "Marks": [85, 72, 90, 65, 78,87]
}

df = pd.DataFrame(data)

print(df)

     Name   Age  Gender Department  Marks
0    Arun  21.0    Male        CSE     85
1    Yoga  22.0    Male        ECE     72
2   Kumar  20.0    Male        CSE     90
3   Shree  23.0  Female        CSE     65
4  Lokesh   NaN    Male         IT     78
5     Nsy  23.0    Male        CSE     87

In [ ]:
df.head()

     Name  Age  Gender Department  Marks
0    Arun   21    Male        CSE     85
1    Yoga   22    Male        ECE     72
2   Kumar   20    Male        CSE     90
3   Shree   23  Female        CSE     65
4  Lokesh   21    Male         IT     78

In [ ]:
df.tail()

     Name  Age  Gender Department  Marks
1    Yoga   22    Male        ECE     72
2   Kumar   20    Male        CSE     90
3   Shree   23  Female        CSE     65
4  Lokesh   21    Male         IT     78
5     Nsy   23    Male        CSE     87

In [ ]:
print(df.shape)

(6, 5)

In [ ]:
print(df.columns)

Index(['Name', 'Age', 'Gender', 'Department', 'Marks'], dtype='object')

In [ ]:
print(df.dtypes)

Name          object
Age            int64
Gender        object
Department    object
Marks          int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         6 non-null      int64
 2   Gender      6 non-null      object
 3   Department  6 non-null      object
 4   Marks       6 non-null      int64
dtypes: int64(2), object(3)
memory usage: 372.0+ bytes

In [ ]:
df.describe()

             Age      Marks
count   6.000000   6.000000
mean   21.666667  79.500000
std     1.211060   9.648834
min    20.000000  65.000000
25%    21.000000  73.500000
50%    21.500000  81.500000
75%    22.750000  86.500000
max    23.000000  90.000000

In [ ]:
print(df["Name"])

0      Arun
1      Yoga
2     Kumar
3     Shree
4    Lokesh
5       Nsy
Name: Name, dtype: object

In [ ]:
print(df[["Name","Marks"]])

     Name  Marks
0    Arun     85
1    Yoga     72
2   Kumar     90
3   Shree     65
4  Lokesh     78
5     Nsy     87

In [ ]:
print(df["Marks"].mean())

79.5

In [ ]:
print(df["Marks"].min())
print(df["Marks"].max())

65
90

In [ ]:
print(df["Gender"].value_counts())

Gender
Male      5
Female    1
Name: count, dtype: int64

In [ ]:
print(df.sort_values("Marks"))

print(df.sort_values("Marks", ascending=False))

     Name  Age  Gender Department  Marks
3   Shree   23  Female        CSE     65
1    Yoga   22    Male        ECE     72
4  Lokesh   21    Male         IT     78
0    Arun   21    Male        CSE     85
5     Nsy   23    Male        CSE     87
2   Kumar   20    Male        CSE     90
     Name  Age  Gender Department  Marks
2   Kumar   20    Male        CSE     90
5     Nsy   23    Male        CSE     87
0    Arun   21    Male        CSE     85
4  Lokesh   21    Male         IT     78
1    Yoga   22    Male        ECE     72
3   Shree   23  Female        CSE     65

In [ ]:
print(df[df["Marks"] > 80])

    Name  Age Gender Department  Marks
0   Arun   21   Male        CSE     85
2  Kumar   20   Male        CSE     90
5    Nsy   23   Male        CSE     87

In [ ]:
print(df[df["Age"]>20])

     Name  Age  Gender Department  Marks
0    Arun   21    Male        CSE     85
1    Yoga   22    Male        ECE     72
3   Shree   23  Female        CSE     65
4  Lokesh   21    Male         IT     78
5     Nsy   23    Male        CSE     87

In [ ]:
print(df[df["Department"]=="CSE"])

    Name  Age  Gender Department  Marks
0   Arun   21    Male        CSE     85
2  Kumar   20    Male        CSE     90
3  Shree   23  Female        CSE     65
5    Nsy   23    Male        CSE     87

In [ ]:
print(df[(df["Marks"] >= 60) & (df["Marks"] <= 80)])

     Name  Age  Gender Department  Marks
1    Yoga   22    Male        ECE     72
3   Shree   23  Female        CSE     65
4  Lokesh   21    Male         IT     78

In [ ]:
print(df[(df["Department"] == "CSE") & (df["Marks"] > 80)])

    Name  Age Gender Department  Marks
0   Arun   21   Male        CSE     85
2  Kumar   20   Male        CSE     90
5    Nsy   23   Male        CSE     87

In [ ]:
print(df.isnull().sum())

Name          0
Age           1
Gender        0
Department    0
Marks         0
dtype: int64

In [ ]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
print(df)

     Name   Age  Gender Department  Marks
0    Arun  21.0    Male        CSE     85
1    Yoga  22.0    Male        ECE     72
2   Kumar  20.0    Male        CSE     90
3   Shree  23.0  Female        CSE     65
4  Lokesh  21.8    Male         IT     78
5     Nsy  23.0    Male        CSE     87

In [ ]:
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])

print(df)

     Name   Age  Gender Department  Marks
0    Arun  21.0    Male        CSE     85
1    Yoga  22.0    Male        ECE     72
2   Kumar  20.0    Male        CSE     90
3   Shree  23.0  Female        CSE     65
4  Lokesh   NaN    Male         IT     78
5     Nsy  23.0    Male        CSE     87

In [ ]:
print(df.duplicated())
df = df.drop_duplicates()

print(df)

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool
     Name   Age  Gender Department  Marks
0    Arun  21.0    Male        CSE     85
1    Yoga  22.0    Male        ECE     72
2   Kumar  20.0    Male        CSE     90
3   Shree  23.0  Female        CSE     65
4  Lokesh   NaN    Male         IT     78
5     Nsy  23.0    Male        CSE     87

In [ ]:
df = df.rename(columns={
    "Name": "Student_Name",
})

print(df)

  Student_Name   Age  Gender Department  Marks
0         Arun  21.0    Male        CSE     85
1         Yoga  22.0    Male        ECE     72
2        Kumar  20.0    Male        CSE     90
3        Shree  23.0  Female        CSE     65
4       Lokesh   NaN    Male         IT     78
5          Nsy  23.0    Male        CSE     87

In [ ]:
df["Result"] = df["Marks"].apply(
    lambda x: "Pass" if x >= 80 else "Fail"
)

print(df)

  Student_Name   Age  Gender Department  Marks Result Age_Group
0         Arun  21.0    Male        CSE     85   Pass     Adult
1         Yoga  22.0    Male        ECE     72   Fail     Adult
2        Kumar  20.0    Male        CSE     90   Pass     Young
3        Shree  23.0  Female        CSE     65   Fail    Senior
4       Lokesh  21.8    Male         IT     78   Fail     Adult
5          Nsy  23.0    Male        CSE     87   Pass    Senior

In [ ]:
df["Age_Group"] = df["Age"].apply(
    lambda x: "Young" if x <= 20
    else "Adult" if x <= 22
    else "Senior"
)

print(df)

  Student_Name   Age  Gender Department  Marks Result Age_Group
0         Arun  21.0    Male        CSE     85   Pass     Adult
1         Yoga  22.0    Male        ECE     72   Fail     Adult
2        Kumar  20.0    Male        CSE     90   Pass     Young
3        Shree  23.0  Female        CSE     65   Fail    Senior
4       Lokesh  21.8    Male         IT     78   Fail     Adult
5          Nsy  23.0    Male        CSE     87   Pass    Senior

In [ ]:
print(df.groupby("Department")["Marks"].mean())

Department
CSE    81.75
ECE    72.00
IT     78.00
Name: Marks, dtype: float64

In [ ]:
print(df.groupby("Department")["Marks"].max())

Department
CSE    90
ECE    72
IT     78
Name: Marks, dtype: int64

In [ ]:
print(df.groupby(["Department", "Gender"]).size())

Department  Gender
CSE         Female    1
            Male      3
ECE         Male      1
IT          Male      1
dtype: int64

In [ ]:
result = df.loc[df.groupby("Department")["Marks"].idxmax()]

print(result)

  Student_Name   Age Gender Department  Marks Result Age_Group
2        Kumar  20.0   Male        CSE     90   Pass     Young
1         Yoga  22.0   Male        ECE     72   Fail     Adult
4       Lokesh  21.8   Male         IT     78   Fail     Adult

In [ ]:
print(df.nlargest(3, "Marks"))

  Student_Name   Age Gender Department  Marks
2        Kumar  20.0   Male        CSE     90
5          Nsy  23.0   Male        CSE     87
0         Arun  21.0   Male        CSE     85

In [ ]:
print(df.groupby("Gender")["Marks"].mean())

Gender
Female    65.0
Male      82.4
Name: Marks, dtype: float64

In [ ]:
avg_Mark=df.groupby("Department")["Marks"].mean()
print(avg_Mark > 70)

Department
CSE    True
ECE    True
IT     True
Name: Marks, dtype: bool

In [ ]:
def grade(marks):
    if marks >= 90:
        return "A"
    elif marks >= 80:
        return "B"
    elif marks >= 70:
        return "C"
    elif marks >= 60:
        return "D"
    else:
        return "F"

df["Grade"] = df["Marks"].apply(grade)

print(df)

  Student_Name   Age  Gender Department  Marks Result Age_Group Grade
0         Arun  21.0    Male        CSE     85   Pass     Adult     B
1         Yoga  22.0    Male        ECE     72   Fail     Adult     C
2        Kumar  20.0    Male        CSE     90   Pass     Young     A
3        Shree  23.0  Female        CSE     65   Fail    Senior     D
4       Lokesh  21.8    Male         IT     78   Fail     Adult     C
5          Nsy  23.0    Male        CSE     87   Pass    Senior     B

In [ ]:
df["Result"] = df["Marks"].apply(
    lambda x: "Pass" if x >= 40 else "Fail"
)

print(df)

  Student_Name   Age  Gender Department  Marks Result Age_Group Grade
0         Arun  21.0    Male        CSE     85   Pass     Adult     B
1         Yoga  22.0    Male        ECE     72   Pass     Adult     C
2        Kumar  20.0    Male        CSE     90   Pass     Young     A
3        Shree  23.0  Female        CSE     65   Pass    Senior     D
4       Lokesh  21.8    Male         IT     78   Pass     Adult     C
5          Nsy  23.0    Male        CSE     87   Pass    Senior     B

In [ ]:
df["Date"] = pd.to_datetime([
    "2026-01-15",
    "2026-02-20",
    "2026-03-10",
    "2026-04-05",
    "2026-05-12",
    "2026-06-18"
])

df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
print(df)

  Student_Name   Age  Gender Department  Marks Result Age_Group Grade  \
0         Arun  21.0    Male        CSE     85   Pass     Adult     B
1         Yoga  22.0    Male        ECE     72   Pass     Adult     C
2        Kumar  20.0    Male        CSE     90   Pass     Young     A
3        Shree  23.0  Female        CSE     65   Pass    Senior     D
4       Lokesh  21.8    Male         IT     78   Pass     Adult     C
5          Nsy  23.0    Male        CSE     87   Pass    Senior     B

        Date  year  Year  Month  Day
0 2026-01-15  2026  2026      1   15
1 2026-02-20  2026  2026      2   20
2 2026-03-10  2026  2026      3   10
3 2026-04-05  2026  2026      4    5
4 2026-05-12  2026  2026      5   12
5 2026-06-18  2026  2026      6   18

In [ ]:
result = df.groupby("Department")["Marks"].agg(
    Average="mean",
    Maximum="max",
    Minimum="min"
)

print(result)

            Average  Maximum  Minimum
Department
CSE           81.75       90       65
ECE           72.00       72       72
IT            78.00       78       78

In [ ]:
pivot = pd.pivot_table(
    df,
    values="Marks",
    index="Department",
    columns="Gender",
    aggfunc="mean"
)

print(pivot)

Gender      Female       Male
Department
CSE           65.0  87.333333
ECE            NaN  72.000000
IT             NaN  78.000000

In [ ]:
import pandas as pd

df = pd.read_csv("Titanic.csv")
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  37.0      0
887                       Graham, Miss. Margaret Edith  female  34.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female  28.0      1
889                              Behr, Mr. Karl Howell    male  19.0      0
890                                Dooley, Mr. Patrick    male  48.0      0

     Parch            Ticket     Fare    Cabin Embarked
0        0         A/5 21171   7.2500      C85        S
1        0          PC 17599  71.2833     C123        C
2        0  STON/O2. 3101282   7.9250      E46        S
3        0            113803  53.1000       G6        S
4        0            373450   8.0500     C103        S
..     ...               ...      ...      ...      ...
886      0            211536  13.0000     E121        S
887      0            112053  30.0000      B77        C
888      2        W./C. 6607  23.4500  B96 B98        Q
889      0            111369  30.0000      D11        C
890      0            370376   7.7500      E77        S

[891 rows x 12 columns]

In [ ]:

print(df.head())
print(df.info())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   C85        S
1      0          PC 17599  71.2833  C123        C
2      0  STON/O2. 3101282   7.9250   E46        S
3      0            113803  53.1000    G6        S
4      0            373450   8.0500  C103        S
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

In [ ]:

df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
df["Cabin"] = df["Cabin"].fillna("Unknown")
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  37.0      0
887                       Graham, Miss. Margaret Edith  female  34.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female  28.0      1
889                              Behr, Mr. Karl Howell    male  19.0      0
890                                Dooley, Mr. Patrick    male  48.0      0

     Parch            Ticket     Fare    Cabin Embarked
0        0         A/5 21171   7.2500      C85        S
1        0          PC 17599  71.2833     C123        C
2        0  STON/O2. 3101282   7.9250      E46        S
3        0            113803  53.1000       G6        S
4        0            373450   8.0500     C103        S
..     ...               ...      ...      ...      ...
886      0            211536  13.0000     E121        S
887      0            112053  30.0000      B77        C
888      2        W./C. 6607  23.4500  B96 B98        Q
889      0            111369  30.0000      D11        C
890      0            370376   7.7500      E77        S

[891 rows x 12 columns]

In [ ]:

df = df.drop_duplicates()
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  37.0      0
887                       Graham, Miss. Margaret Edith  female  34.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female  28.0      1
889                              Behr, Mr. Karl Howell    male  19.0      0
890                                Dooley, Mr. Patrick    male  48.0      0

     Parch            Ticket     Fare    Cabin Embarked
0        0         A/5 21171   7.2500      C85        S
1        0          PC 17599  71.2833     C123        C
2        0  STON/O2. 3101282   7.9250      E46        S
3        0            113803  53.1000       G6        S
4        0            373450   8.0500     C103        S
..     ...               ...      ...      ...      ...
886      0            211536  13.0000     E121        S
887      0            112053  30.0000      B77        C
888      2        W./C. 6607  23.4500  B96 B98        Q
889      0            111369  30.0000      D11        C
890      0            370376   7.7500      E77        S

[891 rows x 12 columns]

In [ ]:

df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Fare"] = pd.to_numeric(df["Fare"], errors="coerce")
df["Survived"] = df["Survived"].astype(int)
df["Pclass"] = df["Pclass"].astype(int)
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  37.0      0
887                       Graham, Miss. Margaret Edith  female  34.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female  28.0      1
889                              Behr, Mr. Karl Howell    male  19.0      0
890                                Dooley, Mr. Patrick    male  48.0      0

     Parch            Ticket     Fare    Cabin Embarked
0        0         A/5 21171   7.2500      C85        S
1        0          PC 17599  71.2833     C123        C
2        0  STON/O2. 3101282   7.9250      E46        S
3        0            113803  53.1000       G6        S
4        0            373450   8.0500     C103        S
..     ...               ...      ...      ...      ...
886      0            211536  13.0000     E121        S
887      0            112053  30.0000      B77        C
888      2        W./C. 6607  23.4500  B96 B98        Q
889      0            111369  30.0000      D11        C
890      0            370376   7.7500      E77        S

[891 rows x 12 columns]

In [ ]:

df["Sex"] = df["Sex"].str.strip().str.upper()
df["Name"] = df["Name"].str.strip().str.upper()
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              BRAUND, MR. OWEN HARRIS    MALE  22.0      1
1    CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...  FEMALE  38.0      1
2                               HEIKKINEN, MISS. LAINA  FEMALE  26.0      0
3         FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)  FEMALE  35.0      1
4                             ALLEN, MR. WILLIAM HENRY    MALE  35.0      0
..                                                 ...     ...   ...    ...
886                              MONTVILA, REV. JUOZAS    MALE  37.0      0
887                       GRAHAM, MISS. MARGARET EDITH  FEMALE  34.0      0
888           JOHNSTON, MISS. CATHERINE HELEN "CARRIE"  FEMALE  28.0      1
889                              BEHR, MR. KARL HOWELL    MALE  19.0      0
890                                DOOLEY, MR. PATRICK    MALE  48.0      0

     Parch            Ticket     Fare    Cabin Embarked
0        0         A/5 21171   7.2500      C85        S
1        0          PC 17599  71.2833     C123        C
2        0  STON/O2. 3101282   7.9250      E46        S
3        0            113803  53.1000       G6        S
4        0            373450   8.0500     C103        S
..     ...               ...      ...      ...      ...
886      0            211536  13.0000     E121        S
887      0            112053  30.0000      B77        C
888      2        W./C. 6607  23.4500  B96 B98        Q
889      0            111369  30.0000      D11        C
890      0            370376   7.7500      E77        S

[891 rows x 12 columns]

In [ ]:

print(df.isnull().sum())
print(df.dtypes)
print(df.duplicated().sum())
print(df)

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object
0
     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              BRAUND, MR. OWEN HARRIS    MALE  22.0      1
1    CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...  FEMALE  38.0      1
2                               HEIKKINEN, MISS. LAINA  FEMALE  26.0      0
3         FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)  FEMALE  35.0      1
4                             ALLEN, MR. WILLIAM HENRY    MALE  35.0      0
..                                                 ...     ...   ...    ...
886                              MONTVILA, REV. JUOZAS    MALE  37.0      0
887                       GRAHAM, MISS. MARGARET EDITH  FEMALE  34.0      0
888           JOHNSTON, MISS. CATHERINE HELEN "CARRIE"  FEMALE  28.0      1
889                              BEHR, MR. KARL HOWELL    MALE  19.0      0
890                                DOOLEY, MR. PATRICK    MALE  48.0      0

     Parch            Ticket     Fare    Cabin Embarked
0        0         A/5 21171   7.2500      C85        S
1        0          PC 17599  71.2833     C123        C
2        0  STON/O2. 3101282   7.9250      E46        S
3        0            113803  53.1000       G6        S
4        0            373450   8.0500     C103        S
..     ...               ...      ...      ...      ...
886      0            211536  13.0000     E121        S
887      0            112053  30.0000      B77        C
888      2        W./C. 6607  23.4500  B96 B98        Q
889      0            111369  30.0000      D11        C
890      0            370376   7.7500      E77        S

[891 rows x 12 columns]

In [ ]:

df.to_csv("cleaned_titanic.csv", index=False)
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              BRAUND, MR. OWEN HARRIS    MALE  22.0      1
1    CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...  FEMALE  38.0      1
2                               HEIKKINEN, MISS. LAINA  FEMALE  26.0      0
3         FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)  FEMALE  35.0      1
4                             ALLEN, MR. WILLIAM HENRY    MALE  35.0      0
..                                                 ...     ...   ...    ...
886                              MONTVILA, REV. JUOZAS    MALE  37.0      0
887                       GRAHAM, MISS. MARGARET EDITH  FEMALE  34.0      0
888           JOHNSTON, MISS. CATHERINE HELEN "CARRIE"  FEMALE  28.0      1
889                              BEHR, MR. KARL HOWELL    MALE  19.0      0
890                                DOOLEY, MR. PATRICK    MALE  48.0      0

     Parch            Ticket     Fare    Cabin Embarked
0        0         A/5 21171   7.2500      C85        S
1        0          PC 17599  71.2833     C123        C
2        0  STON/O2. 3101282   7.9250      E46        S
3        0            113803  53.1000       G6        S
4        0            373450   8.0500     C103        S
..     ...               ...      ...      ...      ...
886      0            211536  13.0000     E121        S
887      0            112053  30.0000      B77        C
888      2        W./C. 6607  23.4500  B96 B98        Q
889      0            111369  30.0000      D11        C
890      0            370376   7.7500      E77        S

[891 rows x 12 columns]